// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD8VMVFqmPsF2h6IatD5kTcmj7OGW0FFE',
    appId: '1:749602175200:web:679f8d9fb9c265e3513885',
    messagingSenderId: '749602175200',
    projectId: 'fir-course-969d6',
    authDomain: 'fir-course-969d6.firebaseapp.com',
    storageBucket: 'fir-course-969d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmL5Uew2O8XhY6YnNq5EMwj1W1b3hOW9c',
    appId: '1:749602175200:android:031d0aa8db8224cf513885',
    messagingSenderId: '749602175200',
    projectId: 'fir-course-969d6',
    storageBucket: 'fir-course-969d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7MSPVZBtE9jb9V5iLRP2sOPZxL_SE0sw',
    appId: '1:749602175200:ios:b99e1c5123c15039513885',
    messagingSenderId: '749602175200',
    projectId: 'fir-course-969d6',
    storageBucket: 'fir-course-969d6.appspot.com',
    androidClientId: '749602175200-1khbm2nvmjm8q9uun5h1vgicvffropk0.apps.googleusercontent.com',
    iosClientId: '749602175200-arfsi3t6i4vj7954j1vj1fv3l414803u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
